general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    # Locks the session right before hardware sleeps
    after_sleep_cmd = hyprctl dispatch dpms on  # Signals both Intel/AMD ports to wake up
}

# Desktop Timer: Securely lock the screen after 10 mins
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Desktop Timer: Put the PC to sleep after 12 mins
listener {
    timeout = 720
    on-timeout = systemctl suspend
}
